### PR TITLE
Fix inconsistent line endings

### LINKED ISSUE #2: Inconsistent line endings
It seems the files in this repo do not use a consistent file format / line ending. I ran into this by cloning the repo and forking into a custom branch in order to customize the Twig templates, and still be able to easily merge from upstream `master` to leverage future fixes / improvements, etc.

In my case, simply changing one line of code in the Responsive Email Twig file resulted in Git `diff`'ing the entire file ...but this only happened on *some* of the modified files, not all. While this may be unavoidable depending on developer IDE / editor preference, it might still be valuable establishing a consistent file format / line endings that devs can then reliably support, especially to avoid potential future conflicts when merging from upstream.

For example, compare some of the files in **default_templates**, such as: `responsive.email.twig` *[dos, CRLF]* or `responsive.cart.twig` *[unix, LF]*, `responsive.receipt.twig` *[dos, CRLF]* etc.

### PR DESCRIPTION
**Pull request by evgenius**
Now all files use Unix style

Fixes #2

### CODE REVIEW

**Comment by evgenius** [comment]
A proof nothing but whitespaces changed:
https://github.com/FoxyCart/2.0-templates/pull/3/files?w=1

**Comment by lukestokes** [comment]
Nicely done, sir. What command do you run for this? I see a lot of files with inconsistent line endings (^M everywhere and such) and I'm not clear how to fix it. With @HinchK @adamjudd and @samifiaz on windows, we'll probably see more of this. Can we clean everything up and get it consistent? That would be nice.

**Comment by lukestokes** [comment]
That last comment was for @evgenius  :)

**Comment by evgenius** [comment]
@lukestokes I just ran `find . -name '*.twig' | xargs fromdos`
Not sure if you have the `fromdos` tool on your Mac. It's a part of the packet `tofrodos`.

**Pull request merged**
